// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductManagmentApp.Models;

#nullable disable

namespace ProductManagmentApp.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20240715124502_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductManagmentApp.Models.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = "de",
                            Name = "Dairy, eggs"
                        },
                        new
                        {
                            Id = "bp",
                            Name = "Bio products"
                        },
                        new
                        {
                            Id = "df",
                            Name = "Dry food"
                        },
                        new
                        {
                            Id = "ab",
                            Name = "Alcoholic beverage"
                        },
                        new
                        {
                            Id = "nad",
                            Name = "Non-alcoholic drink"
                        },
                        new
                        {
                            Id = "ss",
                            Name = "Sweets & snacks"
                        },
                        new
                        {
                            Id = "hy",
                            Name = "Hygiene"
                        },
                        new
                        {
                            Id = "hi",
                            Name = "Household items"
                        },
                        new
                        {
                            Id = "pf",
                            Name = "Pet food"
                        });
                });

            modelBuilder.Entity("ProductManagmentApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ProductManagmentApp.Models.Product", b =>
                {
                    b.HasOne("ProductManagmentApp.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
